version: "3.8"

networks:
  TankBattleNet:
    driver: overlay
services:
  Atlasnet-Controller:
    image: atlasnet-controller-dev
    networks: [TankBattleNet]
    environment:
      - ATLASNET_CONTROLLER_SERVICE_BACKEND=DOCKER
      - ATLASNET_SHARD_DEFAULT_IMAGE=tankbattle-dev:latest
      - ATLASNET_DOCKER_NETWORK_NAME=tankbattle_TankBattleNet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    deploy:
      #labels:
        #atlasnet.role: controller # REQUIRED
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  atlasnet-database:
    image: valkey/valkey:latest
    command: ["valkey-server", "--appendonly", "yes", "--port", "6379"]
    networks: [TankBattleNet]
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: ingress
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  atlasnet-cartograph-frontend:
    image: atlasnet-cartograph-frontend-dev
    networks: [TankBattleNet]
    ports:
      - target : 80
        published: 80
        protocol: tcp
        mode: ingress
    environment:
      - FRONTEND_PORT=4173
      - BACKEND_HOST=atlasnet-cartograph-backend:2000
    deploy:
      mode: replicated
      replicas: 1 
      restart_policy:
        condition: on-failure
 
  atlasnet-cartograph-backend:
    image: atlasnet-cartograph-backend-dev
    networks: [TankBattleNet]
    environment:
      - BACKEND_PORT=2000
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure